/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TCPEchoServer;

import app.TCPEchoServer;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TCPEchoServerTest {
    @Test void appHasAGreeting() {
        TCPEchoServer classUnderTest = new TCPEchoServer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
