/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TCPEchoClient;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TCPEchoClientTest {
    @Test void appHasAGreeting() {
        TCPEchoClient classUnderTest = new TCPEchoClient();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
